<?php

namespace App\Models;

use App\Models\Enums\CryptoEntriesAnalyzeEnum;
use App\Models\Enums\CryptoEntriesTrendEnum;
use App\Models\Enums\CryptoEntriesTrendTypeEnum;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class CryptoEntries extends Model
{
    use HasFactory;

    const CASTS = [
        'trend' => CryptoEntriesTrendEnum::class,
        'trend_type' => CryptoEntriesTrendTypeEnum::class,
    ];
    protected $table = 'crypto_entries';

    protected $casts = [
        'date' => 'date:Y-m-d H:m:s',
    ];
    protected $fillable = ['date', 'trend', 'actif_code', 'trend_type', 'result', 'risk_reward'];

    public function actif(): BelongsTo
    {
        return $this->belongsTo(CryptoEntriesActif::class);
    }

    public function analyze(): BelongsTo
    {
        return $this->belongsTo(CryptoEntriesAnalyze::class);
    }

    public function data(): BelongsTo
    {
        return $this->belongsTo(CryptoEntriesData::class);
    }

    public function opr(): BelongsTo
    {
        return $this->belongsTo(CryptoEntriesOpr::class);
    }

    public function zone(): BelongsTo
    {
        return $this->belongsTo(CryptoEntriesZone::class);
    }

    public function fill(array $attributes)
    {
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
